### ISSUE TITLE
compliance-checker no longer running in IOOS environment

### ISSUE THREAD

**Issue by mwengren** [ioos/notebooks_demos#287]
May not be the right place in the world of conda/conda-forge for this, but I know it will at least be read, so here goes :) :
  
I'm not able to run compliance-checker in the IOOS environment currently.  I did a `conda env update` last Friday since I hadn't used it in awhile, and now I get a missing DLL error in numpy:

```
$ compliance-checker
Traceback (most recent call last):
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Working\local\python\Miniconda2\envs\IOOS\Scripts\compliance-checker-script.py", line 3, in <module>
    import cchecker
  File "C:\Working\local\python\Miniconda2\envs\IOOS\Scripts\cchecker.py", line 6, in <module>
    from compliance_checker.runner import ComplianceChecker, CheckSuite
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\compliance_checker\runner.py", line 9, in <module>
    from compliance_checker.suite import CheckSuite
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\compliance_checker\suite.py", line 12, in <module>
    from netCDF4 import Dataset
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\netCDF4\__init__.py", line 3, in <module>
    from ._netCDF4 import *
  File "include\netCDF4.pxi", line 718, in init netCDF4._netCDF4
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Working\local\python\Miniconda2\envs\IOOS\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

This could have to do with our delicate development environments here (often when I run a conda env update I'm prompted for admin credentials that I don't have, and I have to cancel out of whatever the admin command is trying to do in order for the update command to complete).

I tried removing and re-installing numpy and then repeating the `conda env update` command again, but  no luck.  Does numpy require admin privileges to install a DLL or something? 

It may be that it's just not possible to do development work with conda on our PCs here...

**Comment by ocefpaf** [comment]
Micah, can try downgrading numpy to 1.13? I believe conda-forge's numpy
1.14 with openblas is the culprit here.

**Comment by mwengren** [comment]
@ocefpaf Thanks, that did it.  Must be the new version of numpy is bad on Windows.

**Comment by ocefpaf** [comment]
Not really bad. We need to rebuild all the packages that have numpy
extensions, like netcdf4 in that case.

**Comment by ocefpaf** [comment]
@mwengren I guess we can close this one. Please re-open if you are still seeing this issue.
